apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    backstage.io/kubernetes-id: ${{ values.app_name }}
    backstage.io/kubernetes-namespace: default
spec:
  type: service
  system: ${{ values.system }}
  lifecycle: experimental
  owner: ${{ values.owner }}
  git: ${{ values.git }}
  git_host_url: ${{ values.git_host_url }}
  git_owner_name: ${{ values.git_owner_name }}
